### ISSUE TITLE
Experiment annotation for gas-phase fractionated samples?

### ISSUE THREAD

**Issue by jossmi** [MonashProteomics/FragPipe-Analyst#73]
Hi, I have gas-phase fractionated DIA samples and have updated my experiment-annotation.tsv file to have each fraction within a sample assigned to the same replicate (see attached; the "PAA_X" value represents fraction 1, 2, or 3; also, I have saved it as a .csv because GitHub won't let me attach a .tsv, but I have been using the .tsv format when submitting to FragPipe-Analyst). However, it doesn't appear to be working correctly, as the report lists all fractions as individual samples, rather than combining them together within a sample. Accordingly, there is a lot of data listed as missing, since it seems it is treating fractions as individual samples. I thought I saw a way to handle fractions in the tutorial, but I can't find it now. How can I get FragPipe-Analyst to properly pool fractions within samples?

Thanks,
Josh

[experiment_annotation_example.csv](https://github.com/MonashProteomics/FragPipe-Analyst/files/10709921/experiment_annotation_example.csv)

**Comment by hsiaoyi0504** [comment]
@jossmi Sorry, we currently don't support that. We might improve this in our DIA data processing in the future.
