### ISSUE TITLE
FragPipe Analyst error

### ISSUE THREAD

**Issue by alyssaxin** [MonashProteomics/FragPipe-Analyst#79]
Hi there, 

I've run MSFragger with LFQ IonQuant and have the output files. However, when I input the combined_protein.tsv and experiment_annotation.tsv into Fragpipe-Analyst, it returns an error: : "An error has occurred. Check your logs or contact the app author for clarification." 

I've tried to run with Intensity, MaxLFQ Intensity and Spectral count, but nothing works. Is there a problem with the Fragpipe Analyst server? Let me know.

Thanks!
Alyssa

**Comment by hsiaoyi0504** [comment]
@alyssaxin Could you send us your files? yihsiao@umich.edu
You might want to check if you have some issues in your experiment_annotation as well.

**Comment by hsiaoyi0504** [comment]
So in this case, it's kind of special that you have multiple fractions in one LFQ sample. To make it works, you need to make sure you don't have duplicate sample and sample_name. If you take a look at the combined protein file, there are no multiple columns for the same sample from different fractions.
