### ISSUE TITLE
PCA plot and sample correlation error

### ISSUE THREAD

**Issue by alyssaxin** [MonashProteomics/FragPipe-Analyst#81]
Hello,

I've ran an LFQ experiment and gotten the resulting combined_protein.tsv, however no experiment annotation file was generated. Nonetheless, I've made my own experiment annotation tsv file and inputted this into FragPipe Analyst. I managed to get the significant proteins, volcano plots and other results, but could not get the PCA plot and sample correlation results. The error message appeared: An error has occurred. Check your logs or contact the app author for clarification.

Can I ask for advice on how to get the PCA plot and sample correlation plot?

Cheers,
Alyssa

**Comment by hsiaoyi0504** [comment]
@alyssaxin Is this duplicated with the last one you submitted?
Would you mind sharing the file with me? yihsiao@umich.edu. It's not really possible to know what's the issue based on what you described.

**Comment by hsiaoyi0504** [comment]
Just for future reference. It looks like the data submitted don't have any non-missing values in the intensity columns. It might be because users not correctly configured FragPipe and performed the search.

**Comment by hsiaoyi0504** [comment]
Closed as solved.
