### ISSUE TITLE
Filtering the proteinIDs and adjusted p-value calculation

### ISSUE THREAD

**Issue by pejota66** [MonashProteomics/FragPipe-Analyst#82]
Hello,

Does the Fragpipe-Analyst perform the filtering of the data (i.e. remove contaminants, reverse and protein identified by site)?

What is the statistical method used behind to calculate the p-value which is further adjusted based on BH or local area based)?

Many thanks in advance

**Comment by hsiaoyi0504** [comment]
@pejota66 Sorry for the late response. Yes, we remove contaminants, but I am kind of not sure what do you mean "reverse and protein identified by site"? Would you mind elaborating that? For statistical method, we used Limma as LFQ-Analyst.

**Comment by hsiaoyi0504** [comment]
For more general filtering, those settings are in the advanced options.

**Comment by hsiaoyi0504** [comment]
I am closing this since no further updates.

**Comment by pejota66** [comment]
Sorry for my late response. If I am not mistaken "reverse and protein identified by site" is an option from Perseus software to filter/clean up the data.

Many thanks for your help.
