### ISSUE TITLE
FragPipe Analyst not working 

### ISSUE THREAD

**Issue by pankajdwid** [MonashProteomics/FragPipe-Analyst#83]
See the screen shot of error below:

![image](https://github.com/MonashProteomics/FragPipe-Analyst/assets/46572449/423b50ca-e8cf-40f9-ade5-a1aa4f0bd69a)
![FragPipe analyst error](https://github.com/MonashProteomics/FragPipe-Analyst/assets/46572449/18be0604-c97c-4faa-a0b3-8b5ed07e7c70)

**Comment by hsiaoyi0504** [comment]
Hi @pankajdwid Can you share your files with me? yihsiao@umich.edu. That's kind of hard to see if there is any error in your input files.

**Comment by hsiaoyi0504** [comment]
Closed since no response.
