### ISSUE TITLE
Feature plot doen't seem when using my dataset

### ISSUE THREAD

**Issue by Hayoung-hiro** [MonashProteomics/FragPipe-Analyst#84]
Hi, 
Fragpipe- analyst is an extremely useful tool for me.

However, feature plot didn't appear at all despite selecting some proteins in the result table.
It seems to be a problem of my dataset because it is drawn when using the example dataset.
However, I did not modify the combined_protein.tsv file, which is a FragPipe result file, and the matrix structure is similar to that of example data.
I modified the annotation file because it was multi-friction data, but I don't think this cause a problem.
Any advice would be appreciated.

Thanks

**Comment by Hayoung-hiro** [comment]
This seems to be due to the lack of sample-name column information in the annotation file, while executing the plot_protein function. However, my annotation File matches the structure with example annotation file except for the file column.

**Comment by hsiaoyi0504** [comment]
@Hayoung-hiro Thanks for report the issue, but I don't really fully understand the question. Would you mind sending me an email with your data? yihsiao@umich.edu. It's kind of hard to debug what's the issue based on the description.

**Comment by hsiaoyi0504** [comment]
Just for future reference. The replicate is not correctly set in this case. It hits the upper limit of our color palette. Usually we don't have that many replicates for the same sample.
[experiment_annotation.txt](https://github.com/MonashProteomics/FragPipe-Analyst/files/12589277/experiment_annotation.txt)
