### ISSUE TITLE
Can FragPipe Analyst be used for viewing merged GeLCMS DDA files for LFQ of proteins/peptides?

### ISSUE THREAD

**Issue by lired01** [MonashProteomics/FragPipe-Analyst#85]
We have a project comparing 3 different gel lanes that have been cut into individual digested bands in a typical gel fractionation experiment.  If each lane (A,B,C) is searched as an individual merged experiment consisting of 12 individual digested bands A1-12, B1-12,C12.  So no real replicates for statistics for this very basic shotgun proteomics experiment.
FragPipe viewer opens fine with results but FragePipe Analyst after uploading the combined_protein.tsv and experiment_annotation.tsv  
Give this generic error
Error: An error has occurred. Check your logs or contact the app author for clarification. 

I suspect I have not created or edited the experimental text file correctly or set-up LFQ-MBR workflow correctly? Or that FragPipe Analyst should not be used for this purpose.

Presence absence or intensity would be helpful between samples at Protein ID /peptide level using your interface.

Experimental txt file setup is like this:

file	sample	sample_name	condition	replicate
Y:\data\ingel_A_01.raw	A	A	A	1
Y:\data\ingel_A_02.raw	A	A	A	1
Y:\data\ingel_A_03.raw	A	A	A	1
Y:\data\ingel_A_04.raw	A	A	A	1
Y:\data\ingel_A_05.raw	A	A	A	1
Y:\data\ingel_A_06.raw	A	A	A	1
Y:\data\ingel_A_07.raw	A	A	A	1
Y:\data\ingel_A_08.raw	A	A	A	1
Y:\data\ingel_A_09.raw	A	A	A	1
Y:\data\ingel_A_10.raw	A	A	A	1
Y:\data\ingel_A_11.raw	A	A	A	1
Y:\data\ingel_A_12.raw	A	A	A	1
Y:\data\ingel_B_01.raw	B	B	B	1
Y:\data\ingel_B_02.raw	B	B	B	1
Y:\data\ingel_B_03.raw	B	B	B	1
Y:\data\ingel_B_04.raw	B	B	B	1
Y:\data\ingel_B_05.raw	B	B	B	1
Y:\data\ingel_B_06.raw	B	B	B	1
Y:\data\ingel_B_07.raw	B	B	B	1
Y:\data\ingel_B_08.raw	B	B	B	1
Y:\data\ingel_B_09.raw	B	B	B	1
Y:\data\ingel_B_10.raw	B	B	B	1
Y:\data\ingel_B_11.raw	B	B	B	1
Y:\data\ingel_B_12.raw	B	B	B	1
Y:\data\ingel_C_01.raw	C	C	C	1
Y:\data\ingel_C_02.raw	C	C	C	1
Y:\data\ingel_C_03.raw	C	C	C	1
Y:\data\ingel_C_04.raw	C	C	C	1
Y:\data\ingel_C_05.raw	C	C	C	1
Y:\data\ingel_C_06.raw	C	C	C	1
Y:\data\ingel_C_07.raw	C	C	C	1
Y:\data\ingel_C_08.raw	C	C	C	1
Y:\data\ingel_C_09.raw	C	C	C	1
Y:\data\ingel_C_10.raw	C	C	C	1
Y:\data\ingel_C_11.raw	C	C	C	1
Y:\data\ingel_C_12.raw	C	C	C	1

I have also been unable to connect to the dev server for a while now as it says it is undergoing maintenance or usage capacity. 

Thankyou for your helpful software,

_D

**Comment by hsiaoyi0504** [comment]
@lired01 Thanks for reaching out. I believe it's possible. Could you share your file with me? yihsiao@umich.edu.
And I believe several people doing this like the one in #84. You just need to be careful to make the column name of quantification table (combined_protein.tsv here) and sample name of experiment_annotation.tsv matched.

**Comment by hsiaoyi0504** [comment]
Regarding the dev server issue. We don't really perform maintenance but if someone sends a big trunk of files like big peptide report, it will slow down things and get killed. We are working on setting up some limits but still ongoing. Sorry for the inconvenience.

**Comment by lired01** [comment]
Hello Yi;

Thanks for the quick reply I am guessing these attached tsv files will show my naming errors. You are correct I was able to get Absence/Presence and other features of that page reports when I edited the experiment annotation to only show the three sample names with no fractions 01-12 etc, see dhedit.tsv as compared to the original experiment_annotation.tsv.

***@***.***

I was able to get the results loaded at the now available https://analyst-suites.org/apps/fragpipe-analyst/ site showing standard deviations error as there are no replicates.  This error was reported on Quantification tab.

***@***.***


_Darryl

**Comment by hsiaoyi0504** [comment]
The question was answered, but didn't get further responses.
>Sorry for the late response. Replicate is actually not important in the FrgaPipe-Analyst. That's just more convenient for some users.
But I think you will still need to use different replicate number or just different experiment name like 4580A_band1 etc. when annotating samples.
As you can see in your current combined_protein.tsv file, your different bands from the same sample are merged together having one quantification only.
I don't think that's really what you want. Thanks.

Closing for now.
