### ISSUE TITLE
Could not run DDA data on Fragpipe-Analyst

### ISSUE THREAD

**Issue by YeelonYeoh** [MonashProteomics/FragPipe-Analyst#88]
![image](https://github.com/MonashProteomics/FragPipe-Analyst/assets/155959535/7d5d6696-f439-4d73-90a6-489709f260e0)

**Comment by YeelonYeoh** [comment]
With reference to the problem in the snapshot above, please offer comments to solve the problem.

**Comment by hsiaoyi0504** [comment]
@YeelonYeoh Can you send me your data or at least share the annotation file with me? yihsiao@umich.edu.
It's hard to comment based on the info provided.

**Comment by YeelonYeoh** [comment]
Hi, Hsiaoyi. Here is the screenshot for the annotation file. Unfortunately, I could not upload the file as it is not supported by Github. Please get back to me if you need help.
![image](https://github.com/MonashProteomics/FragPipe-Analyst/assets/155959535/66f8e356-9810-47aa-9f7a-528233206904)

**Comment by YeelonYeoh** [comment]
I am analysing phosphoproteome data acquired by DDA.

**Comment by hsiaoyi0504** [comment]
From the screenshot I can see that your conditions are not correct. Looks like you only have four conditions.

**Comment by YeelonYeoh** [comment]
Thank you for your comments. What should I do to make things work?

**Comment by YeelonYeoh** [comment]
I only have four conditions to compare

**Comment by hsiaoyi0504** [comment]
Just put it into like these four will be fine: Parentialcells_24hrsFOLFX, Parentalcells_untreated, Resistancecells_24hrsFOLFX, andResistancecells_untreated.
