### ISSUE TITLE
Output Volcano Plots for all contrast pairs in PDF report

### ISSUE THREAD

**Issue by jmvarberg** [MonashProteomics/FragPipe-Analyst#89]
Currently the PDF report only includes the volcano plot that is currently displayed/active. I'm wondering if this could be modified to include plots for all contrasts in the analysis? It looks like that functionality may have existed but has been commented out in the report markdown documents (for example, lines 133-136 in DIA_report.Rmd)? Thank you!

**Comment by hsiaoyi0504** [comment]
That should be possible. Will need to find some time implement and test it again. Thanks for the feedback.

**Comment by hsiaoyi0504** [comment]
@jmvarberg Should be available in v0.40 now. Please let me know if it still doesn't work. Thanks.
