### ISSUE TITLE
How to analyse phosphoproteome data acquired using DDA with reference to the proteome data acquired using DIA?

### ISSUE THREAD

**Issue by YeelonYeoh** [MonashProteomics/FragPipe-Analyst#90]
Hi, I want to analyse phosphoproteome data acquired using DDA with reference to the proteome data acquired using DIA. May I get advices for doing so? Perhaps you might refer me to the user's manuals or papers that describe the ways to do so.

**Comment by hsiaoyi0504** [comment]
Have you resolved #88? It's uncommon to acquire them in differently. I guess you could do analysis independently without normalization across them. Anyway, it seems not be the topic supported by current FragPipe-Analyst.

**Comment by YeelonYeoh** [comment]
I have resolved https://github.com/MonashProteomics/FragPipe-Analyst/issues/88
