### ISSUE TITLE
Unable to generate results when analyzing DIA precursor file

### ISSUE THREAD

**Issue by YeelonYeoh** [MonashProteomics/FragPipe-Analyst#93]
![image](https://github.com/MonashProteomics/FragPipe-Analyst/assets/155959535/4caa94b6-d0b2-486c-9d8c-748787a3cf24)
I tried to generate DE results from DIA precursor file but ended up waiting for so long. May I get advice to solve this issue?

**Comment by hsiaoyi0504** [comment]
Hi @YeelonYeoh I never had this issue. Could you send me your files and let me take a look? yihsiao@umich.edu
If it's just taking long time rather than showing an error, I am not sure how much I can help.

**Comment by YeelonYeoh** [comment]
Here, I have attached the protein group file, the precursor file and the annotation file for trial. I want analyse both files together (meaning insert the protein file first and then the precursor file before click 'run') to see how does the analysis results compare to just using the protein group file alone as input for the run.
[Trial_DIA_FragPipe-Analyst.zip](https://github.com/MonashProteomics/FragPipe-Analyst/files/14755099/Trial_DIA_FragPipe-Analyst.zip)

**Comment by hsiaoyi0504** [comment]
@YeelonYeoh I am sorry, but that's not FragPipe-Analyst has supported. May I know what's the idea of using both here?
