### ISSUE TITLE
PTM differential statistics: read combined_site tables?

### ISSUE THREAD

**Issue by patrick-willems** [MonashProteomics/FragPipe-Analyst#95]
Best,

Many thanks for this awesome tool, I was quite amazed at the speed and nice functionalities on the server!
While for sure this is extremely useful for protein and peptide differential statistics, would it be also possible to read in PTM quantifications? For instance starting from combined_site_K_114.0429 for ubiquitination data etc.

Thanks!
Patrick

**Comment by hsiaoyi0504** [comment]
Hi @patrick-willems, currently the FragPipe-Analyst doesn't deal with site-specific PTM data, but it's supported in our R package https://github.com/Nesvilab/FragPipeAnalystR. We didn't test much on ubiquitination, but will be happy to get suggestions and ideas from you and other users like which ubiquitination dataset etc.
