### ISSUE TITLE
command line call

### ISSUE THREAD

**Issue by jflucier** [MonashProteomics/FragPipe-Analyst#97]
Hi,

lets say I have diann results generated through fragpipe or standalone DIANN, is there a way to call fragpipe-analyst directly from the command line on the DIANN results? This would be very usefull for reporting results automaticaly in custom piplines.

If you could pinpoint me to fragpipe-analyst R API calls that would also work for me. I would like to automatically generate plots at the end of my pipeline (PCA, enrichment, missing value, correlation, etc)

thanks for your help in advance,
JF

**Comment by hsiaoyi0504** [comment]
@jflucier That's one of the reasons we created [FragPipeAnalystR](https://www.nesvilab.org/FragPipeAnalystR/). Please check it out and let us know your feedback!

**Comment by jflucier** [comment]
@hsiaoyi0504 

this is awesome. Exactly what I was looking for.

Thank you very much for your help
